import {createDAVClient} from 'tsdav';
import ICAL from 'ical.js';
import {env} from 'cloudflare:workers';
import {database} from './data';
const enc=new TextEncoder();
async function key(){const raw=(env as any).CALENDAR_ENCRYPTION_KEY;if(!raw)throw Error('Calendar encryption is not configured yet.');return crypto.subtle.importKey('raw',Uint8Array.from(atob(raw),c=>c.charCodeAt(0)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encrypt(value:unknown,owner:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(owner)},await key(),enc.encode(JSON.stringify(value)));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(data))})}
export async function connection(owner:string){const row=await database().prepare('SELECT secret FROM connections WHERE owner=?').bind(owner).first<{secret:string}>();if(!row)return null;const data=JSON.parse(row.secret);const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(data.iv),additionalData:enc.encode(owner)},await key(),new Uint8Array(data.data));return JSON.parse(new TextDecoder().decode(raw))}
const safeFetch:typeof fetch=async(input,init)=>{let target=typeof input==='string'?input:input instanceof URL?input.href:input.url;for(let i=0;i<4;i++){const url=new URL(target);if(url.protocol!=='https:'||!(url.hostname==='caldav.icloud.com'||/^p\d+-caldav\.icloud\.com$/.test(url.hostname))||url.port)throw Error('Unexpected calendar server.');const res=await fetch(target,{...init,redirect:'manual',signal:AbortSignal.timeout(20000)});if(![301,302,307,308].includes(res.status))return res;const location=res.headers.get('location');if(!location)throw Error('Calendar redirect failed.');target=new URL(location,target).href;}throw Error('Too many calendar redirects.')};
export async function clientFor(credentials:{email:string;password:string}){return createDAVClient({serverUrl:'https://caldav.icloud.com',credentials:{username:credentials.email,password:credentials.password},authMethod:'Basic',defaultAccountType:'caldav',fetch:safeFetch})}
export async function readCalendar(owner:string){const credentials=await connection(owner);if(!credentials)return {connected:false,events:[],calendars:[]};const client=await clientFor(credentials);const calendars=await client.fetchCalendars();const start=new Date(Date.now()-86400000).toISOString(),end=new Date(Date.now()+14*86400000).toISOString();const events:any[]=[];for(const calendar of calendars){const objects=await client.fetchCalendarObjects({calendar,timeRange:{start,end},expand:true});for(const object of objects){const root=new ICAL.Component(ICAL.parse(object.data));for(const tz of root.getAllSubcomponents('vtimezone')){const id=tz.getFirstPropertyValue('tzid');if(id)ICAL.TimezoneService.register(new ICAL.Timezone({component:tz,tzid:String(id)}))}for(const component of root.getAllSubcomponents('vevent')){if(component.getFirstPropertyValue('status')==='CANCELLED'||component.getFirstPropertyValue('transp')==='TRANSPARENT')continue;const event=new ICAL.Event(component);if(event.isRecurring())throw Error('This calendar returned unexpanded recurring events. Planning has stopped to avoid conflicts.');const uid=event.uid;events.push({id:`icloud:${uid}:${event.startDate.toString()}`,kind:'event',title:event.summary||'Busy',start:event.startDate.toJSDate().toISOString(),end:event.endDate.toJSDate().toISOString(),area:'iCloud',remote:true,taskId:uid?.endsWith('@kalebos')?uid.slice(0,-8):undefined})}}}return {connected:true,events,calendars:calendars.map(c=>String(c.displayName||'Calendar'))}}
export async function publishTask(owner:string,task:any,remove=false){const credentials=await connection(owner);if(!credentials)return false;const client=await clientFor(credentials);const calendars=await client.fetchCalendars();const calendar=calendars.find(c=>String(c.displayName).toLowerCase()==='kalebos');if(!calendar)throw Error('Create a separate iCloud calendar named kalebOS in Apple Calendar, then retry.');const filename=`${task.id}.ics`;const url=new URL(filename,calendar.url.endsWith('/')?calendar.url:calendar.url+'/').href;const objects=await client.fetchCalendarObjects({calendar,objectUrls:[url]});const existing=objects.find(o=>o.url===url);if(existing){const root=new ICAL.Component(ICAL.parse(existing.data));const event=root.getFirstSubcomponent('vevent');if(event?.getFirstPropertyValue('uid')!==task.id+'@kalebos')throw Error('Calendar entry ownership mismatch.')}if(remove){if(existing){const res=await client.deleteCalendarObject({calendarObject:existing});if(!res.ok)throw Error('Calendar deletion failed. Please retry.')}return true}if(!task.start||!task.end)return false;const root=new ICAL.Component(['vcalendar',[],[]]);root.updatePropertyWithValue('version','2.0');root.updatePropertyWithValue('prodid','-//kalebOS//Personal planning//EN');const component=new ICAL.Component('vevent');root.addSubcomponent(component);component.updatePropertyWithValue('uid',task.id+'@kalebos');component.updatePropertyWithValue('dtstamp',ICAL.Time.fromJSDate(new Date(),true));component.updatePropertyWithValue('dtstart',ICAL.Time.fromJSDate(new Date(task.start),true));component.updatePropertyWithValue('dtend',ICAL.Time.fromJSDate(new Date(task.end),true));component.updatePropertyWithValue('summary',task.title);component.updatePropertyWithValue('description',task.body||'Scheduled by kalebOS');const alarm=new ICAL.Component('valarm');alarm.updatePropertyWithValue('action','DISPLAY');alarm.updatePropertyWithValue('description',task.title);alarm.updatePropertyWithValue('trigger',ICAL.Duration.fromString('-PT10M'));component.addSubcomponent(alarm);const response=existing?await client.updateCalendarObject({calendarObject:{...existing,data:root.toString()}}):await client.createCalendarObject({calendar,iCalString:root.toString(),filename,headers:{'If-None-Match':'*'}});if(!response.ok)throw Error('iCloud rejected a calendar change. Refresh and retry; your saved task is retained.');return true}
